// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdzcsgqxsqmmdvpohzim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkemNzZ3F4c3FtbWR2cG9oemltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MTA2MzEsImV4cCI6MjA2MzE4NjYzMX0.BCtgrgN97aiylF967gCDJbA4uRLT2pMhMP-SDkl8nbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);